<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Microsoft.Testing.Platform" Version="2.3.3" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.3.3" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonTests\SchedulerSaturation.CommonTests.csproj" />
    <ProjectReference Include="..\TargetProject\SchedulerSaturation.TargetProject.csproj" />
  </ItemGroup>
</Project>
